### ISSUE TITLE
Creating a branch for Flask-Babel 1

### ISSUE THREAD

**Issue by HeavyTony2** [conda-forge/flask-babel-feedstock#21]
### Comment:

I maintain a package that for now specifically requires Flask-Babel 1. However, the build is now very old, so Pip 24 show this error message at pip check.` Flask-Babel 1.0.0 is not supported on this platform`
For now, my solution was to put a `pip <24` in the run requirements, but I'm pretty confident a fresher build would work with pip >=24.

**Comment by xylar** [comment]
I can make a new build of flask-babel v1.x.x but I do have to ask at what point the effort of maintaining such an old package outweighs the effort you might need to put into supporting a newer version.

**Comment by xylar** [comment]
It was pretty easy to update.  Sorry for being grumpy about it...

**Comment by xylar** [comment]
Unless something goes wrong, the package should be available in about an hour.

**Comment by HeavyTony2** [comment]
> It was pretty easy to update. Sorry for being grumpy about it...

No problem at all, I could have reacted in a similar way myself.

**Comment by xylar** [comment]
Ah, I thought it would close automatically but I now realize that only happens when we merge into `main`.
